joy_teleop:
  ros__parameters:
    move:
      type: topic
      interface_type: geometry_msgs/msg/Twist
      topic_name: tello/cmd_vel
      deadman_buttons: [5]
      axis_mappings:
        linear-x:
          axis: 1
          scale: 100.0
          offset: 0.0
        linear-y:
          axis: 0
          scale: -100.0
          offset: 0.0
        linear-z:
          axis: 4
          scale: 100.0
          offset: 0.0
        angular-z:
          axis: 3
          scale: -100.0
          offset: 0.0

    takeoff:
      type: service
      interface_type: std_srvs/srv/Empty
      service_name: /tello/takeoff
      buttons: [10] # Play

    land:
      type: service
      interface_type: std_srvs/srv/Empty
      service_name: /tello/land
      buttons: [1] # Cerchio
    
    emergency:
      type: service
      interface_type: std_srvs/srv/Empty
      service_name: /tello/emergency
      buttons: [8] # Share

    front_flip:
      type: service
      interface_type: std_srvs/srv/Empty
      service_name: /tello/flip_f
      buttons: [7] # R2

    back_flip:
      type: service
      interface_type: std_srvs/srv/Empty
      service_name: /tello/flip_b
      buttons: [6] # L2

    # right_flip:
    #   type: service
    #   interface_type: std_srvs/srv/Empty
    #   service_name: /tello/flip_r
    #   buttons: [5] # R1
    
    left_flip:
      type: service
      interface_type: std_srvs/srv/Empty
      service_name: /tello/flip_l
      buttons: [4] # L1